/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_kanshan_jni_JniClear */

#ifndef _Included_com_kanshan_jni_JniClear
#define _Included_com_kanshan_jni_JniClear
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_kanshan_jni_JniClear
 * Method:    clear
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_kanshan_jni_JniClear_clear
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
